// import 'dart:io';
// import 'package:dio/dio.dart';
// import 'package:retrofit/retrofit.dart';
//
// part 'api_client.g.dart'; // This will be generated by Retrofit code generator
//
// @RestApi(baseUrl: "https://your-api-endpoint.com/")
// abstract class ApiClient {
//   factory ApiClient(Dio dio, {String baseUrl}) = _ApiClient;
//
//   @POST("upload")
//   @Multipart()
//   Future<HttpResponse> uploadReceipt(
//       @Part() File receipt, // The field name should match the backend's expected name
//       );
// }
